Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [49]:
import numpy as np

In [50]:
n = 10
x = np.arange(n-1, -1, -1)
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [51]:
matrix = np.diag(np.arange(n-1, -1, -1), k=0)
matrix

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [52]:
matrix.sum()

45

Задание 3
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [53]:
import pandas as pd

In [54]:
ratings = pd.read_csv('ml-latest/ratings.csv')
ratings.loc[ratings['rating'] == 5.0].groupby(['movieId']).count().sort_values('rating', ascending=False).head()

userId  rating  timestamp
movieId                           
318       45511   45511      45511
296       35718   35718      35718
356       30280   30280      30280
260       29939   29939      29939
593       29170   29170      29170

Задание 4
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [55]:
data = pd.read_csv('power.csv')
countries = ['Lithuania', 'Estonia', 'Latvia']
categories = [4, 12, 21]
data.loc[data.country.isin(countries) & data.category.isin(categories) & (data.year > 2004) & (data.year < 2011) & (data.quantity > 0)].groupby(['country'])[['quantity']].sum()

quantity
country            
Estonia     63440.0
Latvia      54844.0
Lithuania  122296.0

Задание 5
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [56]:
from numpy import linalg

In [57]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
sol = linalg.solve(a, b)
sol

array([ 0.46666667,  3.84444444, -5.55555556])

In [58]:
np.allclose(np.dot(a, sol), b )

True